#title:All units being referenced by a given source
#tags:map
#defaultView:Map
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT DISTINCT
  ?unit
  ?geometryTitle
  # coordinates in Tora are strings using "," as decimal separator
  (REPLACE(?wgs84_lat, ",", ".") AS ?lat)
  (REPLACE(?wgs84_lon, ",", ".") AS ?lon)
  ?geometryColor
WHERE {
  ?source dcterms:source <https://sok.riksarkivet.se/bildvisning/R0002568_00038> .
  ?source dcterms:references ?unit .
  ?unit <http://www.w3.org/2003/01/geo/wgs84_pos#lat> ?wgs84_lat ;
        <http://www.w3.org/2003/01/geo/wgs84_pos#long> ?wgs84_lon ;
        skos:prefLabel ?geometryTitle .
  BIND("#e8a621" AS ?geometryColor) # replace the default marker color
}
