#title:Images in the National Archives referencing the most units
PREFIX dcterms: <http://purl.org/dc/terms/>
SELECT DISTINCT
  ?sourceMedia
  (COUNT(?unit) AS ?unit_count)
WHERE {
  ?source dcterms:source ?sourceMedia .

  FILTER(STRSTARTS(STR(?sourceMedia), "https://sok.riksarkivet.se/bildvisning/"))
  BIND(CONCAT(REPLACE(STR(?sourceMedia), "https://sok.riksarkivet.se/bildvisning/", "https://lbiiif.riksarkivet.se/v2/arkis!"), "/square/350,/0/default.jpg") AS ?thumbnail)
  
  ?source dcterms:references ?unit .
}
GROUP BY ?sourceMedia
ORDER BY DESC(?unit_count)
